### PR TITLE
update dependency's

### PR DESCRIPTION
**Pull request by cyclomaticcomplexity1981**

### CODE REVIEW

**Comment by blazern** [comment]
Oh boi, those are a lot of updates of the Flutter libraries we use!
Why update everything? :cold_sweat:

**Comment by cyclomaticcomplexity1981** [comment]
i just used pub upgrade. on my side everything worked fine.

**Comment by blazern** [comment]
> i just used pub upgrade. on my side everything worked fine. I mean, there are no major updates...

Well, there's one:
image

I really don't like the idea of updating everything just in the sake of it... It already caused problems in the past.
But okay, hopefully if something is broken we will find it out during manual testing.

**Comment by cyclomaticcomplexity1981** [comment]
ok, i missed that one. But i disagree. I believe if you don't update regularly it will backfire at you (you'll be to far behind). it annoys me we have 14 dependencies that can't be updated and we'll actually have to look at manually at some point. When i open the code in Xcode, i get 30 warning, most of them saying deprecated code is used. That's why i like to keep dependencies up to date, even if it means we'll have to do some refactor.

**Comment by blazern** [comment]
>  When i open the code in Xcode, i get 30 warning, most of them saying deprecated code is used.

Interesting... Does Xcode show warnings when the developer simply uses not the latest versions of some libraries?
Because, when a library of a certain versions is downloaded and used by us, we generally shouldn't see any warnings - it wouldn't make sense for the library to ship deprecated functions, and it wouldn't make sense for us to use those shipped deprecated functions.

> it annoys me we have 14 dependencies that can't be updated and we'll actually have to look at manually at some point.

Well, we would have to look at them manually you're right.
Where as right now we just don't look at them at all... there are about 55 Flutter libraries updates that this Pull Requests brought, and I see a comparable number of updates in `Podfile.lock`.
You probably haven't manually tested all of the code which uses the updated libraries, because it would take you a day to do that. I haven't done that either because of the same reason.
And that's bad - we have features in the app we ourselves rarely use. For example, I very rarely click product's images to see them fullscreen, I would bet you rarely use this feature as well. But it was the feature that broke in the past when we updated all the libraries without manually testing the updated versions.

I don't fully disagree with you - I don't like working with not-the-latest versions of libraries either.
But using not-the-latest-versions has never backfired at me in the past, while updating everything without manual testing has.

**Pull request merged**
